esphome:
  name: sci-spielezimmer
  friendly_name: Keller Spielezimmer SCI

<<: !include hardware/sensecap-indicator.yaml

substitutions:
  # 1. Load theme defaults
  <<: !include theme/defaults.yaml
  <<: !include hardware/sensecap-indicator.yaml

font: !include theme/fonts.yaml

logger:
  hardware_uart: UART0
  level: DEBUG

api:
  encryption:
    key: !secret api_key
  
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  use_address: !secret wifi_ip_address

time:
  - platform: homeassistant
    id: home_time
    timezone: "Europe/Berlin"

globals:
  - id: user_is_interacting
    type: bool
    initial_value: 'false'

script:
  - id: activate_scene
    parameters:
      scene_id: string
    then:
      - homeassistant.service:
          service: scene.turn_on
          data:
            entity_id: !lambda 'return scene_id;'

interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: clock_label
          text: !lambda 'return id(home_time).now().strftime("%H:%M");'

# Home Assistant Entities

sensor:
  - platform: homeassistant
    entity_id: weather.pirateweather
    id: forecast_home_pressure
    attribute: "pressure"
    internal: true
  - platform: homeassistant
    entity_id: weather.pirateweather
    id: forecast_home_temperature
    attribute: "temperature"
    internal: true
  - platform: homeassistant
    entity_id: weather.pirateweather
    id: forecast_home_humidity
    attribute: "humidity"
    internal: true

binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.rr_rainin60min
    id: forecast_home_rain_60min
    internal: true

text:
  - platform: template
    name: "Notifcation Text"
    id: text_notification
    initial_value: ""
    mode: text
    optimistic: true
    max_length: 80
    # on_value:
    #   - script.execute: refresh_epaper

text_sensor:
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: light.keller_spielezimmer_decke
        id: light_spielezimmer_decke
        widget_id: lights_1
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: light.keller_spielezimmer_decke_led
        id: light_spielezimmer_decke_led
        widget_id: lights_2
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: light.keller_spielezimmer_schreibtisch
        id: light_spielezimmer_schreibtisch
        widget_id: lights_3
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: light.werkbank_desklamppro_mi_desk_lamp_pro
        id: werkbank_desklamppro_mi_desk_lamp_pro
        widget_id: lights_4

# UI Definition
lvgl:
  log_level: DEBUG
  style_definitions: !include theme/style.yaml
  
  on_idle:
    timeout: !lambda "return ${idle_timeout} * 1000;"
    then:
      - light.turn_off: backlight
      - lvgl.pause:

  pages:
    - id: main_page
      bg_color: ${color_bg}
      widgets:
        - tabview:
            <<: !include layout/tabview_config.yaml
            tabs:
              - !include
                  file: templates/tabs/overview.yaml
                  vars:
                    tab_id: home
                    name: "Home"
              - !include
                  file: templates/tabs/grid_4_lights.yaml
                  vars:
                    tab_id: lights
                    name: "Lights"
                    l1_name: "Decke"
                    l1_icon: "\U000F0335" # mdi:lightbulb
                    l1_entity: light.keller_spielezimmer_decke
                    l2_name: "Decke LEDs"
                    l2_icon: "\U000F0335" # mdi:lightbulb
                    l2_entity: light.keller_spielezimmer_decke_led
                    l3_name: "Schreibtisch"
                    l3_icon: "\U000F0335" # mdi:lightbulb
                    l3_entity: light.keller_spielezimmer_schreibtisch
                    l4_name: "Werkbank"
                    l4_icon: "\U000F0335" # mdi:lightbulb
                    l4_entity: light.werkbank_desklamppro_mi_desk_lamp_pro
              - !include
                  file: templates/tabs/grid_4_scenes.yaml
                  vars:
                    tab_id: scenes
                    name: "Scenes"
                    s1_name: "Standard"
                    s1_icon: "\U000F0502" # mdi:television
                    s1_entity: scene.spielezimmer_standard
                    s2_name: "Schreibtisch"
                    s2_icon: "\U000F05F2" # mdi:food-fork-drink
                    s2_entity: scene.spielezimmer_schreibtisch
                    s3_name: "Werkbank"
                    s3_icon: "\U000F0099" # mdi:bed-outline
                    s3_entity: scene.spielezimmer_werkbank
                    s4_name: "Sleep"
                    s4_icon: "\U000F0904" # mdi:power-sleep
                    s4_entity: scene.goodnight
