esphome:
  name: sci-spielezimmer
  friendly_name: Keller Spielezimmer SCI

<<: !include hardware/sensecap-indicator.yaml

substitutions:
  # 1. Load theme defaults
  <<: !include theme/defaults.yaml
  <<: !include hardware/sensecap-indicator.yaml

  # 2. Dashboard Configuration
  home_tab_name: "Home"

  lights_tab_name: "Lights"
  light_1_name: "Decke"
  light_1_icon: "\U000F0335" # mdi:lightbulb
  light_1_entity: light.keller_spielezimmer_decke
  light_2_name: "Decke LEDs"
  light_2_icon: "\U000F0335" # mdi:lightbulb
  light_2_entity: light.keller_spielezimmer_decke_led
  light_3_name: "Schreibtisch"
  light_3_icon: "\U000F0335" # mdi:lightbulb
  light_3_entity: light.keller_spielezimmer_schreibtisch
  light_4_name: "Werkbank"
  light_4_icon: "\U000F0335" # mdi:lightbulb
  light_4_entity: light.werkbank_desklamppro_mi_desk_lamp_pro

  scenes_tab_name: "Scenes"
  scene_1_name: "Standard"
  scene_1_icon: "\U000F0502" # mdi:television
  scene_1_entity: scene.spielezimmer_standard
  scene_2_name: "Schreibtisch"
  scene_2_icon: "\U000F05F2" # mdi:food-fork-drink
  scene_2_entity: scene.spielezimmer_schreibtisch
  scene_3_name: "Werkbank"
  scene_3_icon: "\U000F0099" # mdi:bed-outline
  scene_3_entity: scene.spielezimmer_werkbank
  scene_4_name: "Sleep"
  scene_4_icon: "\U000F0904" # mdi:power-sleep
  scene_4_entity: scene.goodnight

  # 3. map light favorite colors per light (can be overridden per deployment)
  <<: !include theme/light_mapping.yaml

font: !include theme/fonts.yaml

logger:
  hardware_uart: UART0
  level: DEBUG

api:
  encryption:
    key: !secret api_key
  
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  use_address: !secret wifi_ip_address

time:
  - platform: homeassistant
    id: home_time
    timezone: "Europe/Berlin"

<<: !include templates/common_logic.yaml

# Home Assistant Entities

sensor:
  # Light Brightness Sensors
  - !include
      file: templates/sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
  - !include
      file: templates/sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
  - !include
      file: templates/sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
  - !include
      file: templates/sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4

text_sensor:
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: templates/virtual_light.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4

  # Light Color Sensors
  - !include
      file: templates/sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: templates/sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: templates/sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: templates/sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4



# UI Definition
lvgl:
  #log_level: DEBUG
  style_definitions: !include theme/style.yaml
  
  on_idle:
    timeout: !lambda "return ${idle_timeout} * 1000;"
    then:
      - light.turn_off: backlight
      - lvgl.pause:

  pages:
    - id: main_page
      bg_color: ${color_bg}
      widgets:
        - !include templates/layouts/standard_3_tabs.yaml
        - !include templates/overlays/light_control.yaml
