globals:
  - id: user_is_interacting
    type: bool
    initial_value: 'false'
  - id: current_light_entity
    type: std::string
    initial_value: '""'

script:
  - id: activate_scene
    parameters:
      scene_id: string
    then:
      - homeassistant.service:
          service: scene.turn_on
          data:
            entity_id: !lambda 'return scene_id;'

  - id: update_weather_desc
    then:
      - lvgl.label.update:
          id: weather_desc_label
          text: !lambda |-
            if (id(forecast_home_rain_60min).state) {
              return "Rain expected";
            } else {
              if (std::isnan(id(forecast_home_humidity).state)) {
                 return "Loading...";
              }
              return "Humidity: " + to_string((int)id(forecast_home_humidity).state) + "%";
            }

interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: clock_label
          text: !lambda 'return id(home_time).now().strftime("%H:%M");'

# Home Assistant Entities

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: forecast_home_rain_60min
    internal: true
    on_state:
      - script.execute: update_weather_desc

sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_pressure
    attribute: "pressure"
    internal: true
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_temperature
    attribute: "temperature"
    internal: true
    on_value:
      - lvgl.label.update:
          id: weather_temp_label
          text: !lambda 'return to_string((int)x) + "°C";'
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_humidity
    attribute: "humidity"
    internal: true
    on_value:
      - script.execute: update_weather_desc

text:
  - platform: template
    name: "Notifcation Text"
    id: text_notification
    initial_value: ""
    mode: text
    optimistic: true
    max_length: 80
