# Data Bridge - View 3 Implementation
# This file connects Home Assistant entities to Global Variables.
# It is decoupled from the UI and does not reference any LVGL object IDs.

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: internal_rain_sensor
    on_state:
      - lambda: 'id(rain_detected) = x;'
      - script.execute: weather_refresh

  - platform: homeassistant
    entity_id: ${motion_sensor_entity}
    id: internal_motion_sensor
    on_press:
      - script.execute: ui_wake_up

  # Light States (1-4)
  - platform: homeassistant
    entity_id: ${light_1_entity}
    id: internal_light_1_state
    on_state:
      - lambda: 'id(light_1_state) = x;'
      - script.execute: light_1_refresh
  - platform: homeassistant
    entity_id: ${light_2_entity}
    id: internal_light_2_state
    on_state:
      - lambda: 'id(light_2_state) = x;'
      - script.execute: light_2_refresh
  - platform: homeassistant
    entity_id: ${light_3_entity}
    id: internal_light_3_state
    on_state:
      - lambda: 'id(light_3_state) = x;'
      - script.execute: light_3_refresh
  - platform: homeassistant
    entity_id: ${light_4_entity}
    id: internal_light_4_state
    on_state:
      - lambda: 'id(light_4_state) = x;'
      - script.execute: light_4_refresh

sensor:
  # Weather & Environment
  - platform: homeassistant
    id: internal_temp_sensor
    entity_id: ${weather_entity}
    attribute: "temperature"
    on_value:
      - lambda: |-
          id(temp_val) = x;
          id(temp_chart_values).push_back(x);
          if (id(temp_chart_values).size() > ${chart_max_points}) {
            id(temp_chart_values).erase(id(temp_chart_values).begin());
          }
      - script.execute: weather_refresh

  - platform: homeassistant
    id: internal_hum_sensor
    entity_id: ${weather_entity}
    attribute: "humidity"
    on_value:
      - lambda: 'id(hum_val) = x;'
      - script.execute: weather_refresh

  # Power Sensor
  - platform: homeassistant
    id: internal_power_sensor
    entity_id: ${power_sensor_entity}
    on_value:
      - lambda: |-
          id(power_val) = x;
          id(chart_values).push_back(x);
          if (id(chart_values).size() > ${chart_max_points}) {
            id(chart_values).erase(id(chart_values).begin());
          }
      - script.execute: power_refresh

  # Media Player Position/Duration
  - platform: homeassistant
    id: internal_media_pos
    entity_id: ${media_player_entity}
    attribute: "media_position"
    on_value:
      - lambda: 'id(media_player_pos_val) = x;'
      - script.execute: media_refresh
  
  - platform: homeassistant
    id: internal_media_dur
    entity_id: ${media_player_entity}
    attribute: "media_duration"
    on_value:
      - lambda: 'id(media_player_dur_val) = x;'
      - script.execute: media_refresh

  # Sensor Group 1
  - platform: homeassistant
    id: internal_sg1_s1
    entity_id: ${sg1_s1_entity}
    on_value:
      - lambda: 'id(sg1_s1_val) = x;'
      - script.execute: sg1_refresh
  - platform: homeassistant
    id: internal_sg1_s2
    entity_id: ${sg1_s2_entity}
    on_value:
      - lambda: 'id(sg1_s2_val) = x;'
      - script.execute: sg1_refresh
  - platform: homeassistant
    id: internal_sg1_s3
    entity_id: ${sg1_s3_entity}
    on_value:
      - lambda: 'id(sg1_s3_val) = x;'
      - script.execute: sg1_refresh

  # Sensor Group 2
  - platform: homeassistant
    id: internal_sg2_s1
    entity_id: ${sg2_s1_entity}
    on_value:
      - lambda: 'id(sg2_s1_val) = x;'
      - script.execute: sg2_refresh
  - platform: homeassistant
    id: internal_sg2_s2
    entity_id: ${sg2_s2_entity}
    on_value:
      - lambda: 'id(sg2_s2_val) = x;'
      - script.execute: sg2_refresh
  - platform: homeassistant
    id: internal_sg2_s3
    entity_id: ${sg2_s3_entity}
    on_value:
      - lambda: 'id(sg2_s3_val) = x;'
      - script.execute: sg2_refresh

  # Light Brightness (1-4)
  - platform: homeassistant
    id: internal_light_1_brightness
    entity_id: ${light_1_entity}
    attribute: brightness
    on_value:
      - lambda: 'id(light_1_brightness_val) = x;'
      - script.execute: light_1_refresh
  - platform: homeassistant
    id: internal_light_2_brightness
    entity_id: ${light_2_entity}
    attribute: brightness
    on_value:
      - lambda: 'id(light_2_brightness_val) = x;'
      - script.execute: light_2_refresh
  - platform: homeassistant
    id: internal_light_3_brightness
    entity_id: ${light_3_entity}
    attribute: brightness
    on_value:
      - lambda: 'id(light_3_brightness_val) = x;'
      - script.execute: light_3_refresh
  - platform: homeassistant
    id: internal_light_4_brightness
    entity_id: ${light_4_entity}
    attribute: brightness
    on_value:
      - lambda: 'id(light_4_brightness_val) = x;'
      - script.execute: light_4_refresh

text_sensor:
  # Media Player Info
  - platform: homeassistant
    id: internal_media_title
    entity_id: ${media_player_entity}
    attribute: "media_title"
    on_value:
      - lambda: 'id(media_player_title_val) = x;'
      - script.execute: media_refresh

  - platform: homeassistant
    id: internal_media_state
    entity_id: ${media_player_entity}
    on_value:
      - lambda: 'id(media_player_state_val) = x;'
      - script.execute: media_refresh

  # Weather State
  - platform: homeassistant
    id: internal_weather_state
    entity_id: ${weather_entity}
    on_value:
      - lambda: 'id(weather_state_val) = x;'
      - script.execute: weather_refresh

  # Light RGB Colors (1-4)
  - platform: homeassistant
    id: internal_light_1_rgb
    entity_id: ${light_1_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            id(light_1_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          }
      - script.execute: light_1_refresh

  - platform: homeassistant
    id: internal_light_2_rgb
    entity_id: ${light_2_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            id(light_2_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          }
      - script.execute: light_2_refresh

  - platform: homeassistant
    id: internal_light_3_rgb
    entity_id: ${light_3_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            id(light_3_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          }
      - script.execute: light_3_refresh

  - platform: homeassistant
    id: internal_light_4_rgb
    entity_id: ${light_4_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            id(light_4_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          }
      - script.execute: light_4_refresh
