# Home Assistant Entities

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: forecast_home_rain_60min
    internal: true
    on_state:
      - script.execute: update_weather_ui

  - platform: homeassistant
    entity_id: ${motion_sensor_entity}
    id: external_motion_sensor
    internal: true
    on_press:
      - script.execute: ui_wake_up

sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_temperature
    attribute: "temperature"
    internal: true
    on_value:
      - script.execute: update_weather_ui
      - script.execute:
          id: update_label_text
          label_obj: !lambda "return id(sensor_group_widget_s1_val);"
          text: !lambda "return to_string((int)x) + \"°C\";"
      - lambda: |-
          id(temp_chart_values).push_back(x);
          if (id(temp_chart_values).size() > ${chart_max_points}) {
            id(temp_chart_values).erase(id(temp_chart_values).begin());
          }
      # - script.execute:
      #     id: update_graph
      #     chart_obj: !lambda "return id(home_temp_graph_chart_container);"
      #     label_obj: !lambda "return id(home_temp_graph_value_label);"
      #     values: !lambda "return &id(temp_chart_values);"
      #     unit: "°C"

  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_humidity
    attribute: "humidity"
    internal: true
    on_value:
      - script.execute: update_weather_ui
      - script.execute:
          id: update_label_text
          label_obj: !lambda "return id(sensor_group_widget_s2_val);"
          text: !lambda "return to_string((int)x) + \"%\";"

  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_pressure
    attribute: "pressure"
    internal: true
    on_value:
      - script.execute: update_weather_ui

  - platform: homeassistant
    entity_id: ${power_sensor_entity}
    id: power_sensor
    internal: true
    on_value:
      - script.execute:
          id: update_label_text
          label_obj: !lambda "return id(sensor_group_widget_s3_val);"
          text: !lambda "return to_string((int)x) + \"W\";"
      - lambda: |-
          id(chart_values).push_back(x);
          if (id(chart_values).size() > ${chart_max_points}) {
            id(chart_values).erase(id(chart_values).begin());
          }
      - script.execute:
          id: update_graph
          chart_obj: !lambda "return id(home_power_graph_chart_container);"
          label_obj: !lambda "return id(home_power_graph_value_label);"
          values: !lambda "return &id(chart_values);"
          unit: "W"

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_player_position
    attribute: "media_position"
    internal: true
    on_value:
      - lambda: |-
          if (!std::isnan(id(media_player_duration).state) && id(media_player_duration).state > 0) {
            int progress = (int)((x / id(media_player_duration).state) * 100);
            lv_bar_set_value(id(media_player_widget_seekbar), progress, LV_ANIM_ON);
          }
  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_player_duration
    attribute: "media_duration"
    internal: true

text_sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_state
    internal: true
    on_value:
      - script.execute: update_weather_ui

  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_player_title
    attribute: "media_title"
    internal: true
    on_value:
      - script.execute:
          id: update_label_text
          label_obj: !lambda "return id(media_player_widget_title);"
          text: !lambda "return x;"
  - platform: homeassistant
    entity_id: ${media_player_entity}
    id: media_player_state
    internal: true
    on_value:
      - script.execute: update_media_player_ui

text:
  - platform: template
    name: "Notification Text"
    id: text_notification
    initial_value: ""
    mode: text
    optimistic: true
    max_length: 120
