sensor:
  # Light Brightness Sensors
  - !include
      file: ../sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
  - !include
      file: ../sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
  - !include
      file: ../sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
  - !include
      file: ../sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4

text_sensor:
  - !include
      file: ../devices/virtual_light.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: ../devices/virtual_light.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: ../devices/virtual_light.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: ../devices/virtual_light.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4

  # Light Color Sensors
  - !include
      file: ../sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: ../sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: ../sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: ../sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4
