# Home Assistant Entities

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: forecast_home_rain_60min
    internal: true
    on_state:
      - script.execute: update_weather_ui

sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_pressure
    attribute: "pressure"
    internal: true
    on_value:
      - script.execute: update_weather_ui
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_temperature
    attribute: "temperature"
    internal: true
    on_value:
      - script.execute: update_weather_ui
      - lambda: |-
          id(temp_chart_values).push_back(x);
          if (id(temp_chart_values).size() > ${chart_max_points}) {
            id(temp_chart_values).erase(id(temp_chart_values).begin());
          }
      - script.execute:
          id: update_graph
          chart_obj: !lambda "return id(home_temp_graph_chart_container);"
          label_obj: !lambda "return id(home_temp_graph_value_label);"
          values: !lambda "return &id(temp_chart_values);"
          unit: "°C"
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_humidity
    attribute: "humidity"
    internal: true
    on_value:
      - script.execute: update_weather_ui

  - platform: homeassistant
    entity_id: ${power_sensor_entity}
    id: power_sensor
    internal: true
    on_value:
      - lambda: |-
          id(chart_values).push_back(x);
          if (id(chart_values).size() > ${chart_max_points}) {
            id(chart_values).erase(id(chart_values).begin());
          }
      - script.execute:
          id: update_graph
          chart_obj: !lambda "return id(home_power_graph_chart_container);"
          label_obj: !lambda "return id(home_power_graph_value_label);"
          values: !lambda "return &id(chart_values);"
          unit: "W"

text_sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_state
    internal: true
    on_value:
      - script.execute: update_weather_ui

text:
  - platform: template
    name: "Notifcation Text"
    id: text_notification
    initial_value: ""
    mode: text
    optimistic: true
    max_length: 80
