# Data Bridge - View 3 Implementation
# This file connects Home Assistant entities to Global Variables.
# It is decoupled from the UI and does not reference any LVGL object IDs.

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: internal_rain_sensor
    on_state:
      - lambda: 'id(rain_detected) = x;'
      - script.execute: weather_refresh

  - platform: homeassistant
    entity_id: ${motion_sensor_entity}
    id: internal_motion_sensor
    on_press:
      - script.execute: ui_wake_up

  # Light States (1-4)
  - platform: homeassistant
    entity_id: ${light_1_entity}
    id: internal_light_1_state
    on_state:
      - lambda: 'ESP_LOGI("data_bridge", "Light 1 state changed to: %s", x ? "ON" : "OFF");'
      - lambda: 'id(light_1_state) = x;'
      - script.execute: light_1_refresh
  - platform: homeassistant
    entity_id: ${light_2_entity}
    id: internal_light_2_state
    on_state:
      - lambda: 'ESP_LOGI("data_bridge", "Light 2 state changed to: %s", x ? "ON" : "OFF");'
      - lambda: 'id(light_2_state) = x;'
      - script.execute: light_2_refresh
  - platform: homeassistant
    entity_id: ${light_3_entity}
    id: internal_light_3_state
    on_state:
      - lambda: 'ESP_LOGI("data_bridge", "Light 3 state changed to: %s", x ? "ON" : "OFF");'
      - lambda: 'id(light_3_state) = x;'
      - script.execute: light_3_refresh
  - platform: homeassistant
    entity_id: ${light_4_entity}
    id: internal_light_4_state
    on_state:
      - lambda: 'ESP_LOGI("data_bridge", "Light 4 state changed to: %s", x ? "ON" : "OFF");'
      - lambda: 'id(light_4_state) = x;'
      - script.execute: light_4_refresh

sensor:
  # Weather & Environment
  - platform: homeassistant
    id: internal_temp_sensor
    entity_id: ${weather_entity}
    attribute: "temperature"
    on_value:
      - lambda: |-
          id(temp_val) = x;
      - script.execute: weather_refresh

  - platform: homeassistant
    id: internal_hum_sensor
    entity_id: ${weather_entity}
    attribute: "humidity"
    on_value:
      - lambda: 'id(hum_val) = x;'
      - script.execute: weather_refresh

  - platform: homeassistant
    id: internal_pressure_sensor
    entity_id: ${weather_entity}
    attribute: "pressure"
    on_value:
      - lambda: 'id(pressure_val) = x;'
      - script.execute: weather_refresh

  # Graph Sensors
  - platform: homeassistant
    id: internal_graph_1_sensor
    entity_id: ${graph_1_entity}
    on_value:
      - lambda: |-
          id(power_val) = x;
          id(graph_1_values).push_back(x);
          if (id(graph_1_values).size() > ${chart_max_points}) {
            id(graph_1_values).erase(id(graph_1_values).begin());
          }
      - script.execute: power_refresh

  - platform: homeassistant
    id: internal_graph_2_sensor
    entity_id: ${graph_2_entity}
    on_value:
      - lambda: |-
          id(graph_2_values).push_back(x);
          if (id(graph_2_values).size() > ${chart_max_points}) {
            id(graph_2_values).erase(id(graph_2_values).begin());
          }
      - script.execute: graph_2_refresh


  # Media Player Position/Duration
  - platform: homeassistant
    id: internal_media_pos
    entity_id: ${media_player_entity}
    attribute: "media_position"
    on_value:
      - lambda: 'id(media_player_pos_val) = x;'
      - script.execute: media_refresh
  
  - platform: homeassistant
    id: internal_media_dur
    entity_id: ${media_player_entity}
    attribute: "media_duration"
    on_value:
      - lambda: 'id(media_player_dur_val) = x;'
      - script.execute: media_refresh

text_sensor:
  # Media Player Info
  - platform: homeassistant
    id: internal_media_title
    entity_id: ${media_player_entity}
    attribute: "media_title"
    on_value:
      - lambda: 'id(media_player_title_val) = x;'
      - script.execute: media_refresh

  - platform: homeassistant
    id: internal_media_artist
    entity_id: ${media_player_entity}
    attribute: "media_artist"
    on_value:
      - lambda: 'id(media_player_artist_val) = x;'

  - platform: homeassistant
    id: internal_media_state
    entity_id: ${media_player_entity}
    on_value:
      - lambda: 'id(media_player_state_val) = x;'
      - script.execute: media_refresh

  # Light Brightness (1-4)
  - platform: homeassistant
    id: internal_light_1_brightness
    entity_id: ${light_1_entity}
    attribute: brightness
    on_value:
      - lambda: |-
          if (x == "None" || x == "") {
            id(light_1_brightness_val) = 0;
          } else {
            id(light_1_brightness_val) = strtof(x.c_str(), nullptr);
          }
      - script.execute: light_1_refresh
  - platform: homeassistant
    id: internal_light_2_brightness
    entity_id: ${light_2_entity}
    attribute: brightness
    on_value:
      - lambda: |-
          if (x == "None" || x == "") {
            id(light_2_brightness_val) = 0;
          } else {
            id(light_2_brightness_val) = strtof(x.c_str(), nullptr);
          }
      - script.execute: light_2_refresh
  - platform: homeassistant
    id: internal_light_3_brightness
    entity_id: ${light_3_entity}
    attribute: brightness
    on_value:
      - lambda: |-
          if (x == "None" || x == "") {
            id(light_3_brightness_val) = 0;
          } else {
            id(light_3_brightness_val) = strtof(x.c_str(), nullptr);
          }
      - script.execute: light_3_refresh
  - platform: homeassistant
    id: internal_light_4_brightness
    entity_id: ${light_4_entity}
    attribute: brightness
    on_value:
      - lambda: |-
          if (x == "None" || x == "") {
            id(light_4_brightness_val) = 0;
          } else {
            id(light_4_brightness_val) = strtof(x.c_str(), nullptr);
          }
      - script.execute: light_4_refresh

  # Weather State
  - platform: homeassistant
    id: internal_weather_state
    entity_id: ${weather_entity}
    on_value:
      - lambda: 'id(weather_state_val) = x;'
      - script.execute: weather_refresh

  # Light RGB Colors (1-4)
  - platform: homeassistant
    id: internal_light_1_rgb
    entity_id: ${light_1_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            // Clamp RGB values to valid range (0-255) to prevent undefined behavior
            r = r < 0 ? 0 : (r > 255 ? 255 : r);
            g = g < 0 ? 0 : (g > 255 ? 255 : g);
            b = b < 0 ? 0 : (b > 255 ? 255 : b);
            id(light_1_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          } else {
            ESP_LOGW("data_bridge", "Failed to parse RGB for light_1: %s", x.c_str());
          }
      - script.execute: light_1_refresh

  - platform: homeassistant
    id: internal_light_2_rgb
    entity_id: ${light_2_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            // Clamp RGB values to valid range (0-255) to prevent undefined behavior
            r = r < 0 ? 0 : (r > 255 ? 255 : r);
            g = g < 0 ? 0 : (g > 255 ? 255 : g);
            b = b < 0 ? 0 : (b > 255 ? 255 : b);
            id(light_2_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          } else {
            ESP_LOGW("data_bridge", "Failed to parse RGB for light_2: %s", x.c_str());
          }
      - script.execute: light_2_refresh

  - platform: homeassistant
    id: internal_light_3_rgb
    entity_id: ${light_3_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            // Clamp RGB values to valid range (0-255) to prevent undefined behavior
            r = r < 0 ? 0 : (r > 255 ? 255 : r);
            g = g < 0 ? 0 : (g > 255 ? 255 : g);
            b = b < 0 ? 0 : (b > 255 ? 255 : b);
            id(light_3_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          } else {
            ESP_LOGW("data_bridge", "Failed to parse RGB for light_3: %s", x.c_str());
          }
      - script.execute: light_3_refresh

  - platform: homeassistant
    id: internal_light_4_rgb
    entity_id: ${light_4_entity}
    attribute: rgb_color
    on_value:
      - lambda: |-
          int r, g, b;
          if (sscanf(x.c_str(), "[%d,%d,%d]", &r, &g, &b) == 3 || 
              sscanf(x.c_str(), "(%d,%d,%d)", &r, &g, &b) == 3 ||
              sscanf(x.c_str(), "%d,%d,%d", &r, &g, &b) == 3) {
            // Clamp RGB values to valid range (0-255) to prevent undefined behavior
            r = r < 0 ? 0 : (r > 255 ? 255 : r);
            g = g < 0 ? 0 : (g > 255 ? 255 : g);
            b = b < 0 ? 0 : (b > 255 ? 255 : b);
            id(light_4_color_val) = (uint32_t(r) << 16) | (uint32_t(g) << 8) | uint32_t(b);
          } else {
            ESP_LOGW("data_bridge", "Failed to parse RGB for light_4: %s", x.c_str());
          }
      - script.execute: light_4_refresh

  # Sensor Group 1
  - platform: homeassistant
    id: internal_sg1_s1
    entity_id: ${sg1_s1_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg1_s1_val) = "${sg1_s1_map_on}";
          else if (x == "off") id(sg1_s1_val) = "${sg1_s1_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
            // Integer: remove decimal
             id(sg1_s1_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg1_s1_unit}";
          }
          else id(sg1_s1_val) = x + "${sg1_s1_unit}";
      - script.execute: sg1_refresh
  - platform: homeassistant
    id: internal_sg1_s2
    entity_id: ${sg1_s2_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg1_s2_val) = "${sg1_s2_map_on}";
          else if (x == "off") id(sg1_s2_val) = "${sg1_s2_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
             id(sg1_s2_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg1_s2_unit}";
          }
          else id(sg1_s2_val) = x + "${sg1_s2_unit}";
      - script.execute: sg1_refresh
  - platform: homeassistant
    id: internal_sg1_s3
    entity_id: ${sg1_s3_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg1_s3_val) = "${sg1_s3_map_on}";
          else if (x == "off") id(sg1_s3_val) = "${sg1_s3_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
             id(sg1_s3_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg1_s3_unit}";
          }
          else id(sg1_s3_val) = x + "${sg1_s3_unit}";
      - script.execute: sg1_refresh

  # Sensor Group 2
  - platform: homeassistant
    id: internal_sg2_s1
    entity_id: ${sg2_s1_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg2_s1_val) = "${sg2_s1_map_on}";
          else if (x == "off") id(sg2_s1_val) = "${sg2_s1_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
             id(sg2_s1_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg2_s1_unit}";
          }
          else id(sg2_s1_val) = x + "${sg2_s1_unit}";
      - script.execute: sg2_refresh
  - platform: homeassistant
    id: internal_sg2_s2
    entity_id: ${sg2_s2_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg2_s2_val) = "${sg2_s2_map_on}";
          else if (x == "off") id(sg2_s2_val) = "${sg2_s2_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
             id(sg2_s2_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg2_s2_unit}";
          }
          else id(sg2_s2_val) = x + "${sg2_s2_unit}";
      - script.execute: sg2_refresh
  - platform: homeassistant
    id: internal_sg2_s3
    entity_id: ${sg2_s3_entity}
    on_value:
      - lambda: |-
          if (x == "on") id(sg2_s3_val) = "${sg2_s3_map_on}";
          else if (x == "off") id(sg2_s3_val) = "${sg2_s3_map_off}";
          else if (strtof(x.c_str(), nullptr) == (int)strtof(x.c_str(), nullptr)) {
             id(sg2_s3_val) = to_string((int)strtof(x.c_str(), nullptr)) + "${sg2_s3_unit}";
          }
          else id(sg2_s3_val) = x + "${sg2_s3_unit}";
      - script.execute: sg2_refresh

