globals:
  - id: user_is_interacting
    type: bool
    initial_value: 'false'
  - id: current_light_entity
    type: std::string
    initial_value: '""'

script:
  - id: activate_scene
    parameters:
      scene_id: string
    then:
      - homeassistant.service:
          service: scene.turn_on
          data:
            entity_id: !lambda 'return scene_id;'

  - id: update_overlay_colors
    then:
      - lambda: |-
          std::string current = id(current_light_entity);
          int32_t c1 = ${fav_1_default_bg};
          int32_t c2 = ${fav_2_default_bg};
          int32_t c3 = ${fav_3_default_bg};
          int32_t c4 = ${fav_4_default_bg};

          if (current == "${light_1_entity}") {
             c1 = ${light_1_fav_1_bg}; c2 = ${light_1_fav_2_bg}; c3 = ${light_1_fav_3_bg}; c4 = ${light_1_fav_4_bg};
          } else if (current == "${light_2_entity}") {
             c1 = ${light_2_fav_1_bg}; c2 = ${light_2_fav_2_bg}; c3 = ${light_2_fav_3_bg}; c4 = ${light_2_fav_4_bg};
          } else if (current == "${light_3_entity}") {
             c1 = ${light_3_fav_1_bg}; c2 = ${light_3_fav_2_bg}; c3 = ${light_3_fav_3_bg}; c4 = ${light_3_fav_4_bg};
          } else if (current == "${light_4_entity}") {
             c1 = ${light_4_fav_1_bg}; c2 = ${light_4_fav_2_bg}; c3 = ${light_4_fav_3_bg}; c4 = ${light_4_fav_4_bg};
          }

          lv_obj_set_style_bg_color(id(btn_fav_1), lv_color_hex(c1), 0);
          lv_obj_set_style_bg_color(id(btn_fav_2), lv_color_hex(c2), 0);
          lv_obj_set_style_bg_color(id(btn_fav_3), lv_color_hex(c3), 0);
          lv_obj_set_style_bg_color(id(btn_fav_4), lv_color_hex(c4), 0);

  - id: update_weather_desc
    then:
      - lvgl.label.update:
          id: weather_desc_label
          text: !lambda |-
            if (id(forecast_home_rain_60min).state) {
              return "Rain expected";
            } else {
              if (std::isnan(id(forecast_home_humidity).state)) {
                 return "Loading...";
              }
              return "Humidity: " + to_string((int)id(forecast_home_humidity).state) + "%";
            }

interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: clock_label
          text: !lambda 'return id(home_time).now().strftime("%H:%M");'

# Home Assistant Entities

binary_sensor:
  - platform: homeassistant
    entity_id: ${rain_sensor_entity}
    id: forecast_home_rain_60min
    internal: true
    on_state:
      - script.execute: update_weather_desc

sensor:
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_pressure
    attribute: "pressure"
    internal: true
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_temperature
    attribute: "temperature"
    internal: true
    on_value:
      - lvgl.label.update:
          id: weather_temp_label
          text: !lambda 'return to_string((int)x) + "°C";'
  - platform: homeassistant
    entity_id: ${weather_entity}
    id: forecast_home_humidity
    attribute: "humidity"
    internal: true
    on_value:
      - script.execute: update_weather_desc

  # Light Brightness Sensors
  - !include
      file: sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
  - !include
      file: sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
  - !include
      file: sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
  - !include
      file: sensors/light_brightness.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4

text_sensor:
  - !include
      file: virtual_light.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: virtual_light.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: virtual_light.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: virtual_light.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4

  # Light Color Sensors
  - !include
      file: sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_1_entity}
        id: lights_1
        widget_id: lights_1
  - !include
      file: sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_2_entity}
        id: lights_2
        widget_id: lights_2
  - !include
      file: sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_3_entity}
        id: lights_3
        widget_id: lights_3
  - !include
      file: sensors/light_color.yaml
      vars:
        hass_entity_id: ${light_4_entity}
        id: lights_4
        widget_id: lights_4

text:
  - platform: template
    name: "Notifcation Text"
    id: text_notification
    initial_value: ""
    mode: text
    optimistic: true
    max_length: 80
